### PR TITLE
one more thing!

### PR DESCRIPTION
**Pull request by jinpark**
@ilyakava is this what you meant for https://github.com/ilyakava/pongbot/issues/6#issuecomment-51146243

### CODE REVIEW

**Comment by ilyakava** [comment]
This is nice too! But I was referring to a line like: https://github.com/ilyakava/pongbot/blob/master/app.js#L139
There are 6 lines in total like this

**Comment by jinpark** [comment]
Ohhhhhh. Yea I can do that

**Comment by ilyakava** [comment]
just pushed some squashed changes that I found in your fork. Consider it merge-able once i write specs

**Comment by ilyakava** [comment]
Haven't gotten around to writing specs :(
merging anyway

**Comment by dblock** [comment]
Integrated upstream via https://github.com/andrewvy/slack-pongbot/pull/28.

**Pull request merged**
